# Copyright (c) 2026 Brendan Bank
# SPDX-License-Identifier: BSD-2-Clause

"""Alembic helpers for hosts using ``HostForeignKey``.

Wire this into the host's ``alembic/env.py``::

    from app.host_sdk.alembic import emit_host_foreign_keys

    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        version_table=VERSION_TABLE,
        process_revision_directives=emit_host_foreign_keys,
        ...,
    )

What it does
------------

Walks every ``MigrationScript`` alembic just generated, finds
``CreateTableOp`` / ``AddColumnOp`` ops on host tables, and for each
column carrying an ``atrium_host_fks`` marker (placed there by
:class:`app.host_sdk.db.HostForeignKey`) emits a matching
``ForeignKeyConstraint`` / ``CreateForeignKeyOp``. The generated
migration ends up identical to one a host integrator would write by
hand following the casa-style workaround — except autogenerated.

What it does not do
-------------------

- It does not register a model-level ``ForeignKey`` against the
  host's metadata. The whole point of the marker is to keep the
  mapper from seeing a cross-metadata FK.
- It does not validate that the target table exists in atrium's
  metadata. Atrium's metadata isn't loaded at autogenerate time on
  the host side (the host's env.py only imports its own ``HostBase``)
  so we can't cheaply check. Mistyped target names surface at
  ``alembic upgrade`` time as a MySQL FK error, which is loud
  enough.
"""
from __future__ import annotations

import logging
from typing import Any, cast

import sqlalchemy as sa
from alembic.operations import ops

from app.host_sdk.db import INFO_KEY, HostFKSpec

log = logging.getLogger(__name__)


def emit_host_foreign_keys(
    context: Any,
    revision: Any,
    directives: list[ops.MigrationScript],
) -> None:
    """``process_revision_directives`` callback.

    Mutates ``directives`` in-place: any host column carrying a
    ``HostForeignKey`` marker grows a matching FK constraint /
    ``CreateForeignKeyOp`` so the autogenerated migration includes
    the database-level foreign key.
    """
    del context, revision  # unused; signature is alembic's
    for script in directives:
        upgrade = getattr(script, "upgrade_ops", None)
        if upgrade is not None:
            _walk(upgrade.ops)


def _walk(op_list: list[ops.MigrateOperation]) -> None:
    """Visit every op, including those nested inside ``ModifyTableOps``.

    ``ops`` is mutated: ``CreateTableOp`` may have constraints
    appended to its ``columns`` list, and an ``AddColumnOp`` may have
    a sibling ``CreateForeignKeyOp`` inserted after it.
    """
    i = 0
    while i < len(op_list):
        op = op_list[i]
        new_ops_after: list[ops.MigrateOperation] = []
        if isinstance(op, ops.CreateTableOp):
            _augment_create_table(op)
        elif isinstance(op, ops.AddColumnOp):
            new_ops_after.extend(_fk_ops_for_added_column(op))
        elif isinstance(op, ops.ModifyTableOps):
            _walk(op.ops)
        if new_ops_after:
            op_list[i + 1 : i + 1] = new_ops_after
            i += len(new_ops_after)
        i += 1


def _augment_create_table(op: ops.CreateTableOp) -> None:
    """Append a ``ForeignKeyConstraint`` per host-FK marker on the new table."""
    # ``op.columns`` is typed as ``Sequence`` upstream but is a list at
    # runtime (alembic appends to it during autogenerate).
    columns = cast("list[Any]", op.columns)
    for col in list(columns):
        if not isinstance(col, sa.Column):
            continue
        for spec in _specs_on(col):
            parsed = _split_target(spec.target)
            if parsed is None:
                continue
            ref_table, ref_col = parsed
            columns.append(
                sa.ForeignKeyConstraint(
                    [col.name],
                    [f"{ref_table}.{ref_col}"],
                    name=spec.name,
                    ondelete=spec.ondelete,
                    onupdate=spec.onupdate,
                )
            )


def _fk_ops_for_added_column(
    op: ops.AddColumnOp,
) -> list[ops.MigrateOperation]:
    """Build a ``CreateForeignKeyOp`` for each marker on an added column."""
    out: list[ops.MigrateOperation] = []
    col = op.column
    for spec in _specs_on(col):
        parsed = _split_target(spec.target)
        if parsed is None:
            continue
        ref_table, ref_col = parsed
        out.append(
            ops.CreateForeignKeyOp(
                constraint_name=spec.name,
                source_table=op.table_name,
                referent_table=ref_table,
                local_cols=[col.name],
                remote_cols=[ref_col],
                ondelete=spec.ondelete,
                onupdate=spec.onupdate,
            )
        )
    return out


def _specs_on(col: sa.Column[Any]) -> tuple[HostFKSpec, ...]:
    raw = col.info.get(INFO_KEY, ())
    return tuple(raw)


def _split_target(target: str) -> tuple[str, str] | None:
    """Parse ``"users.id"`` into ``("users", "id")``.

    A malformed marker (no dot, empty halves) logs a warning and
    returns ``None`` so the caller skips it. Loud-enough on misuse
    without crashing the migration generation — autogenerate is
    interactive, the operator sees the warning.
    """
    table, _, column = target.partition(".")
    if not table or not column:
        log.warning(
            "host_sdk: skipping HostForeignKey with malformed target %r — "
            "expected '<table>.<column>'",
            target,
        )
        return None
    return table, column


__all__ = ["emit_host_foreign_keys"]
