# Copyright (c) 2026 Brendan Bank
# SPDX-License-Identifier: BSD-2-Clause

"""Host-side declarative helpers.

A host bundle declares its models on a separate ``DeclarativeBase``
so atrium's alembic chain and the host's alembic chain don't fight
each other. SQLAlchemy resolves ``ForeignKey("users.id")`` within a
single ``MetaData`` though, so a column-level FK from a host table to
an atrium table (``users``, ``roles``, ...) blows up at mapper-init
with a cross-metadata reference error.

The historical workaround was: declare the column with no
``ForeignKey()`` and add a ``ForeignKeyConstraint`` by hand in the
alembic migration. It works, but every new host re-discovers it,
autogenerate doesn't write it, and there's no record on the model
that the column is logically a foreign key.

``HostForeignKey`` closes that loop. It's a no-op as far as the
mapper is concerned (no FK is registered against atrium's metadata)
but stamps a marker into the column's ``info`` dict that the alembic
hook in ``app.host_sdk.alembic`` reads at autogenerate time and
turns into a ``ForeignKeyConstraint`` op. Runtime FK behaviour ends
up identical to a normal model-level FK because the constraint
exists in the database — it just isn't represented on the ORM side.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from sqlalchemy.sql.schema import SchemaItem

INFO_KEY = "atrium_host_fks"
"""Key under which ``HostForeignKey`` markers live on
``Column.info``. Tuple-shaped so a single column with multiple
``HostForeignKey()`` markers (rare, but supported) round-trips
predictably through the alembic hook."""


@dataclass(frozen=True)
class HostFKSpec:
    """Captured metadata for a deferred host foreign key.

    The mapper never sees this — only the alembic autogenerate hook
    does. ``target`` follows the standard SQLAlchemy
    ``"<table>.<column>"`` shape (``"users.id"``).
    """

    target: str
    ondelete: str | None = None
    onupdate: str | None = None
    name: str | None = None


class HostForeignKey(SchemaItem):
    """Declare a foreign key from a host table to an atrium table.

    Drops in where you'd put a ``ForeignKey`` on a normal model::

        class Booking(HostBase):
            __tablename__ = "bookings"
            id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
            created_by_user_id: Mapped[int] = mapped_column(
                Integer,
                HostForeignKey("users.id", ondelete="RESTRICT"),
                nullable=False,
            )

    No ``ForeignKey`` is registered against the host's metadata, so
    the mapper sees a plain integer column. The column's ``info``
    carries the spec; the alembic ``emit_host_foreign_keys`` hook
    picks it up at autogenerate time and emits a
    ``ForeignKeyConstraint`` op against ``target``.

    The constraint name is generated by alembic / SQLAlchemy if you
    don't pass ``name=``. Hosts using strict naming conventions can
    pass one through.
    """

    def __init__(
        self,
        target: str,
        *,
        ondelete: str | None = None,
        onupdate: str | None = None,
        name: str | None = None,
    ) -> None:
        self._spec = HostFKSpec(
            target=target, ondelete=ondelete, onupdate=onupdate, name=name
        )

    @property
    def spec(self) -> HostFKSpec:
        return self._spec

    def _set_parent(self, parent: Any, **kw: Any) -> None:
        # SQLAlchemy calls this when the column is constructed. We
        # stash the spec on Column.info so the alembic hook (and any
        # other introspection code) can find every host FK on a
        # column without re-walking schema items.
        existing = parent.info.setdefault(INFO_KEY, ())
        parent.info[INFO_KEY] = (*existing, self._spec)


__all__ = ["INFO_KEY", "HostFKSpec", "HostForeignKey"]
